### ISSUE TITLE
Build complete, frontend not appearing

### ISSUE THREAD

**Issue by thineswaran** [lorenzomiscoli/tutorials#1]
Hello. The spring-angular-deployment project explained at  https://lorenzomiscoli.com/deploying-spring-boot-and-angular-as-a-single-app/ builds properly, but frontend webpage doesn't appear when I navigate to http://localhost:8080

I'm getting the output as shown in the screenshot.

What could be the reason?

After building, I ran the jar file as mentioned in the article. Embedded Tomcat runs on port 8080, but the index.html page in frontend doesn't appear
<img width="1028" alt="Screenshot 2024-04-26 at 2 34 19 AM" src="https://github.com/lorenzomiscoli/tutorials/assets/17696912/b31cffda-9349-4032-a506-57935a328bff">

**Comment by lorenzomiscoli** [comment]
Hi, what version of Angular are you using? 

Could you please paste your package.json?
